import { ReportSubstance } from './ReportSubstance';

export const enum ReportActivity {
  ALPHASTIM100 = 704,
  BREATHING = 470,
  CHANTING = 456,
  CONFERENCES = 361,
  CRANIAL_ELECTROTHERAPY_STIMULATION = 705,
  DEVICES = 302,
  DREAMS = 85,
  DRUG_TESTING = 59,
  ENDOGENOUS = 86,
  FAMILIES = 661,
  FASTING = 178,
  FLOATATION_TANK = 369,
  GUIDING = 184,
  HUMOR = 469,
  HYPERVENTILATION = 141,
  MAGNETIC_DEVICES = 283,
  MEDITATION = 128,
  MIGRAINES = 154,
  MIND_MACHINE_DEVICES = 301,
  MINDFULNESS = 405,
  MUSIC = 457,
  NITROGEN_NARCOSIS = 189,
  OBE = 332,
  POLICE_CUSTOMS = 60,
  RITUAL = 129,
  SLEEP_DEPRIVATION = 140,
  SOUND_NON_MUSIC = 547,
  SWEATING = 341,
  TRANSCRANIAL_FOCUSED_ULTRASOUND = 884,
  YOGA_BODYWORK = 202,
}

export const activityEnumMap = {
  breathing: ReportActivity.BREATHING,
  chanting: ReportActivity.CHANTING,
  conferences: ReportActivity.CONFERENCES,
  dreams: ReportActivity.DREAMS,
  endogenous: ReportActivity.ENDOGENOUS,
  families: ReportActivity.FAMILIES,
  fasting: ReportActivity.FASTING,
  floatationTanks: ReportActivity.FLOATATION_TANK,
  meditation: ReportActivity.MEDITATION,
  music: ReportActivity.MUSIC,
  obe: ReportActivity.OBE,
  policeAndCustoms: ReportActivity.POLICE_CUSTOMS,
  ritual: ReportActivity.RITUAL,
  sound: ReportActivity.SOUND_NON_MUSIC,
  sweat: ReportActivity.SWEATING,
  yoga: ReportActivity.YOGA_BODYWORK,
};
