import WordRule from './WordRule';
import WordListRule from './WordListRule';

const titles = [
  new WordRule('mr.|mr'),
  new WordRule('miss.|miss'),
  new WordRule('mrs.|mrs'),
  new WordRule('ms.|ms'),
  new WordRule('mx.|mx'),
  new WordRule('sir'),
  new WordRule('sire'),
  new WordRule('gentlemen'),
  new WordRule('mistress'),
  new WordRule("madam|ma'am"),
  new WordRule('gentlemen'),
  new WordRule('dame'),
  new WordRule('lord'),
  new WordRule('lady'),
  new WordRule('esq.|esq|esquire'),
  new WordRule('hon.|hon|honorable'),
  new WordRule('dr.|dr'),
  new WordRule('professor|prof.|prof'),
  new WordRule('father|fr.|fr'),
  new WordRule('pastor|pr.|pr'),
  new WordRule('brother|br.|b'),
  new WordRule('sister|sr.|sr'),
  new WordRule('elder'),
  new WordRule('rabbi'),
  new WordRule('reverend|rev.|rev'),
  new WordRule('rebbetzin'),
  new WordRule('imam'),
  new WordRule('shaykh'),
  new WordRule('mufti'),
  new WordRule('hafiz'),
  new WordRule('qari'),
  new WordRule('mawlana'),
  new WordRule('haji'),
  new WordRule('sayyid|sayyidah'),
  new WordRule('sharif'),
  new WordRule('venerable'),
  new WordRule('bishop'),
  new WordRule('baron|baroness'),
  new WordRule('count|countess'),
  new WordRule('viscount'),
  new WordRule('earl'),
  new WordRule('king'),
  new WordRule('queen'),
  new WordRule('prince'),
  new WordRule('princess'),
  new WordRule('duke|duchess'),
  new WordRule('principal'),
  new WordRule('president|pres.|pres'),
  new WordRule('master'),
  new WordRule('warden'),
  new WordRule('dean'),
  new WordRule('regent'),
  new WordRule('rector'),
  new WordRule('provost'),
  new WordRule('director'),
  new WordRule('officer'),
  new WordRule('trooper'),
  new WordRule('sheriff'),
  new WordRule('deputy'),
  new WordRule('airman'),
  new WordRule('seamen'),
  new WordRule('sergeant|sgt.|sgt'),
  new WordRule('lieutenant|lt.|lt'),
  new WordRule('captain|cpt.|cpt'),
  new WordRule('corporal|cpl.|cpl'),
  new WordRule('commander|cmdr.|cmdr'),
  new WordRule('colonel|col.|col'),
  new WordRule('general|gen.|gen'),
  new WordRule('admiral|adm.|adm'),
  new WordRule('chaplain'),
  new WordRule('private|prt.|prt'),
  new WordRule('major|maj.|maj'),
];

const entityRules = {
  ANIMAL: [
    new WordListRule([new WordRule('german'), new WordRule('shepherd')]).withDepth(1),
    new WordListRule([new WordRule('boa'), new WordRule('constrictor')]).withDepth(1),
  ],
  CHARACTER: [
    //Handles things like "Mr. Smith"
    new WordListRule([
      new WordRule(titles.map((title) => title.word).join('|')),
      new WordRule(null).withEntity('CHARACTER'),
    ]).withDepth(1),
  ],
  OTHER: [
    new WordListRule([new WordRule(null).withRegExp(/^\d+$/), new WordRule('%')]).withDepth(1),
  ],
};

export { entityRules };
